### PR TITLE
use Maven Central mirror hosted on Google Cloud Storage for faster build

### LINKED ISSUE #168: Faster build by using Maven Central mirror hosted on Google Cloud Storage
## Overview (Required)
- Maven Central mirror hosted on Google Cloud Storage
- https://storage-download.googleapis.com/maven-central/index.html

### PR DESCRIPTION
**Pull request by ma2gedev**
## Issue
- close #168

## Overview (Required)
- use Maven Central mirror following to https://storage-download.googleapis.com/maven-central/index.html

## Links
- https://storage-download.googleapis.com/maven-central/index.html

## Screenshot

There is no screenshot but build speed faster than before, I could not measure accurately though.

The following is synchronization time on my MacBook Air. I only measured once.

Before | After
:--: | :--:
synced successfully 10m 29s 199ms | synced successfully 8m 30s 38ms

### CODE REVIEW

**Comment by takahirom** [comment]
Since CI's server is overseas, how about judging whether it is CI server or not like this?

def isCi = System.getenv("CI") == "true"

```
        google()
        if (!isCi) { maven { url "https://maven-central-asia.storage-download.googleapis.com/repos/central/data/" } }
        jcenter()
```

**Comment by ma2gedev** [comment]
> Since CI's server is overseas, how about judging whether it is CI server or not like this?

Wow, I have not noticed about CI. That is a cool idea so I will check it later tonight in JST.

**Comment by ma2gedev** [comment]
I added `isCi` as extra property but please tell me if there is any other good way.

**Comment by ma2gedev** [comment]
Thank you so much!

**Pull request merged**
