### PR TITLE
Add requirements to README

### PR DESCRIPTION
**Pull request by takahirom**
## Issue
- close https://github.com/DroidKaigi/conference-app-2019/issues/240#issuecomment-452303392

## Overview (Required)
- For build this project

### CODE REVIEW

**Comment by takahirom** [comment]
@nukka123 How about this? 👀

**Comment by nukka123** [comment]
@takahirom 
Nice!

I think that it is more good if the following description is added.
(sorry, i can not write fluent english...)

Check out following status.
`Preference` > `Languages & Frameworks` > `Kotlin Updates`

**Comment by takahirom** [comment]
> (sorry, i can not write fluent english...)

me too 😄 

I will add that! Thanks 👍

**Comment by nukka123** [comment]
@takahirom 
👍

**Pull request merged**
