### PR TITLE
Make `api-impl` to Kotlin Multiplatform module

### PR DESCRIPTION
**Pull request by kikuchy**
## Issue
- A step of #136

## Overview (Required)
- Make `:data:api-impl` to Kotlin Multiplatform module.
- Keep injectable API clients constructers.
- No iOS implementation yet.
    - It's difficult for me to get the value of `API_ENDPOINT` in build.gradle from iOS implementation.
    - Please give me some ideas 😢

## Links
- https://kotlinlang.org/docs/tutorials/native/mpp-ios-android.html
- https://ktor.io/clients/http-client/features/user-agent.html

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Probably I feel that passing ENDPOINT is good 👍 (But If we can find good solution for it, I want to replace.)

**Comment by jmatsu** [comment]
I know BuildConfig is android-specific... 🙇  
I'm not sure how to get such build-time conditional values on iOS/web/Native of multi-platform projects but it would be okay to declare a common class which has api endpoint values if possible.

I'm a more newbie of multiplatform than other newbies... so this is just an idea.
If we can use macro for iOS project and write a binding to Kotlin's actual implementation, then the code would be like below.

```
// common
internal expect fun apiEndpoint(): String
```

```
// android
internal actual fun apiEndpoint(): String {
    return BuildConfig.API_ENDPOINT
}

// ios
internal actual fun apiEndpoint(): String {
    return <endpoint from obj c>
}
```

**Comment by takahirom** [comment]
Any way we can merge this!
If you add iOS code, You can consider this 👍 
https://github.com/DroidKaigi/conference-app-2019/pull/246#issuecomment-452247536

**Comment by takahirom** [comment]
We are waiting for your next contribution 🥇

**Comment by kikuchy** [comment]
Thanks a lot!

I will take this https://github.com/DroidKaigi/conference-app-2019/pull/246#issuecomment-452247536 way if I can implement...!

**Pull request merged**
