### PR TITLE
feat: SharedElement Transition for SpeakerIcon

### LINKED ISSUE #185: Shared element transition
## Overview (Required)
- We can do shared element transition when going to the speaker screen.

### PR DESCRIPTION
**Pull request by verno3632**
## Issue
- close #185

## Overview (Required)
- SharedElement Transition for Speaker Icon from (Session Detail/Search) Screen to Speaker Screen
- We may consider about NON SharedElement Transition for Speaker Icon
  - It looks that non SharedElements appear soon and Speaker Icon moves on them.
- There is no transition when back from Speaker Screen
  - I need more investigation

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
How about adding ` <fade />` ?

**Comment by verno3632** [comment]
@takahirom Do you mean adding fade-in transition for Speaker Screen?
<image src="https://user-images.githubusercontent.com/1014262/52206226-e906a400-28bc-11e9-8d07-f35469e3958e.gif" width=300 />

**Comment by verno3632** [comment]
I think it is difficult to implement the SharedElement transition when back from Speaker Screen.
SharedElement transition needs to wait for the target view visible, but I have no idea to subscribe the events after groupie update RecyclerView’s children view ( = speaker icon on SessionDetail/Search screen) asynchronously.

**Comment by takahirom** [comment]
> Do you mean adding fade-in transition for Speaker Screen?
Yes! looks good 👍

**Comment by takahirom** [comment]
LGTM 👍

**Pull request merged**
