### PR TITLE
Show session start time on header for iOS App

### LINKED ISSUE #592: Show session start time for iOS App
## Kind (Required)

- Other

 ## Overview (Required)

- 
image

- https://github.com/DroidKaigi/conference-app-2019/pull/583#issuecomment-456580809

セッションの開始時間を表示するには、開始時間毎に`[Session]`を分ける必要があると思います。
例えば、下のようにクラスを用意して、`[Session]`を`[Hogehoge]`として分配し、
それぞれの時間毎に`UITableView`の`section`で分けて`UITableViewHeaderFooterView`を用意して上げれば出来ると思います。

```
struct Hogehoge {
    let startDayText: String
    let startTime: Double
    var sessions: [Session]
}
```

### PR DESCRIPTION
**Pull request by t-kashima**
## Issue

- close #592

## Overview (Required)

- Show session start time on header for iOS App

## Links

- 

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
In Android App, this margin exists for the time text.
How about delete margin?
image

**Comment by t-kashima** [comment]
@takahirom Thank you for your review😀
OK, I tried deleting the left margin.

**Comment by ShoMasegi** [comment]
There is two way to design this scene. Which plan is better?
I implemented this cell with PlanB.
Sorry for interfering..🙇‍♂️

| Plan A | Plan B |
|:---:|:---:|
|||

**Comment by t-kashima** [comment]
Thank you for your comment and the screenshot!
I was thinking which plan to implement. me too😊

**Comment by takahirom** [comment]
Thanks 👍 
I think Plan B is more like DroidKaigi Design. It's great 💯

**Comment by t-kashima** [comment]
@takahirom @ShoMasegi 
Thank you for your review and advice🙇‍♂️

**Comment by ShoMasegi** [comment]
Look Great To Me!!🙌

**Pull request merged**
