### PR TITLE
Added ripple effect to ImageButton of about screen

### PR DESCRIPTION
**Pull request by NUmeroAndDev**
## Overview (Required)
- Added ripple effect to ImageButton of about screen.  

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by NUmeroAndDev** [comment]
I thought it was difficult to press because the size of the button is small.

**Comment by jmatsu** [comment]
> I thought it was difficult to press because the size of the button is small.

Indeed. 🤔 
Could you please add `12dp` to paddings and minus `12dp` from margins?

**Comment by takahirom** [comment]
🆒

**Comment by NUmeroAndDev** [comment]
4dp に変わっていたの見落としていました 🙇 
UI 設計書にあわせつつ 4dp の padding を追加しました。

**Comment by jmatsu** [comment]
@NUmeroAndDev 
すみません、最初 16dp と書いてました 🙇 ありがとうございます！

**Comment by NUmeroAndDev** [comment]
🤔 

```
> Could not download kotlin-metadata.jar (me.eugeniomarletti.kotlin.metadata:kotlin-metadata:1.4.0)
      > Could not get resource 'https://jcenter.bintray.com/me/eugeniomarletti/kotlin/metadata/kotlin-metadata/1.4.0/kotlin-metadata-1.4.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/me/eugeniomarletti/kotlin/metadata/kotlin-metadata/1.4.0/kotlin-metadata-1.4.0.jar'. Received status code 502 from server: Bad Gateway
```

**Comment by takahirom** [comment]
Probably, Now jCenter is not working 😭

**Comment by takahirom** [comment]
Thank you for cool touch feedback 🆒

**Pull request merged**
