### PR TITLE
replace session_label with search_label

### PR DESCRIPTION
**Pull request by tarumzu**
## Issue
- none

## Overview (Required)
-Timeline will be displayed when the search icon's long tap

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by panpanini** [comment]
could you add a link to the issue number as well? :pray:

**Comment by takahirom** [comment]
Nice catch 🐱

**Comment by takahirom** [comment]
I think the issue number is not needed 😉

**Comment by tarumzu** [comment]
@panpanini sorry🙏. This issue was not made

**Pull request merged**
