### PR TITLE
Rename FireStore to Firestore

### LINKED ISSUE #103: Rename FireStore to Firestore
## Overview (Required)
- "Firestore" is correct.

## Links
- https://firebase.google.com/docs/firestore/

### PR DESCRIPTION
**Pull request by furusin**
## Issue
- close #103 

## Overview (Required)
- Rename FireStore.kt to Firestore.kt 2f5dc86
- rename FireStoreComponent.kt to FirestoreComponent.kt 5322dcc
- Rename FireStoreComponentModule.kt to FirestoreComponentModule.kt 6854f0f

## Links
- https://firebase.google.com/docs/firestore/

## Screenshot
not required

### CODE REVIEW

**Comment by furusin** [comment]
🤔

**Comment by jmatsu** [comment]
The class names have been done though, their files have not been renamed correctly. 
Could you please rename files too?

**Comment by furusin** [comment]
gush, thanks alot. I will.

**Comment by furusin** [comment]
Umm...
In my project, the filename `FireStoreComponent` and `FireStoreComponentModule` have changed to `FireStore` already.
I couldn't figure out what I should do.

**Comment by tomoya0x00** [comment]
If you are working on Windows please refer to below.
https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Comment by furusin** [comment]
thanks @tomoya0x00 
I tried the command, then worked only for `FireStoreComponent.kt`.
`FireStoreComponentModule.kt` has been error like below:
```
 git mv -f FireStoreComponentModule.kt FirestoreComponentModule.kt
fatal: bad source, source=data/firestore-impl/src/main/java/io/github/droidkaigi/confsched2019/data/firestore/FireStoreComponentModule.kt, destination=data/firestore-impl/src/main/java/io/github/droidkaigi/confsched2019/data/firestore/FirestoreComponentModule.kt
```

**Comment by tomoya0x00** [comment]
🤔 

Can you try this?
```
 git mv -f FirestoreComponentModule.kt FireStoreComponentModule.kt
 git mv -f FireStoreComponentModule.kt FirestoreComponentModule.kt
```

**Comment by furusin** [comment]
didn't work even if tried with `a.kt` ... 🤔

**Comment by jmatsu** [comment]
How about moving the file through a temporary file?

```
 git mv FirestoreComponentModule.kt FirestoreComponentModuleTemp.kt
 git mv FirestoreComponentModuleTemp.kt FirestoreComponentModule.kt
```

**Comment by takahirom** [comment]
You can use c8c91b8af5d8cfd6b84b6dde25ce8b3e03be3a37 commit 🙏

**Comment by takahirom** [comment]
Thank you for rename 📛

**Pull request merged**
