### PR TITLE
Implemented font on info screen

### PR DESCRIPTION
**Pull request by NUmeroAndDev**
## Issue
- None

## Overview (Required)
- Implemented font on info screen.
- ~~EmojiTextView -> EmojiAppCompatTextView~~
~~Because fontFamily is not applied in EmojiTextView.~~

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry, It text is currently English. But probably it will become Japanese text.

**Comment by NUmeroAndDev** [comment]
@takahirom 
> Sorry, It text is currently English. But probably it will become Japanese text.

Which font is used by Gallery, should not specify font for title and description?  

First Item | Second Item
:--: | :--:
 | 

`TextOppearance.App.Caption` was used for `content_text`, so the noto font is applied. 
(元から `TextOppearance.App.Caption` が `content_text` に使われていたため、noto のフォントが反映されていました。)

Can I apply fonts only to date text?

**Comment by takahirom** [comment]
> Can I apply fonts only to date text?

Sorry, Please do it 🙇

**Comment by NUmeroAndDev** [comment]
@takahirom 
Only font was applied for date text.
I'm sorry to make changes that not need. 🙇

**Comment by takahirom** [comment]
Thanks for apply details! 🆒 
Your PR will make this app high quality 👍

**Pull request merged**
