### PR TITLE
Replace LocaleMessage with LocaledString

### LINKED ISSUE #290: Replace LocaleMessage with LocaledString
## Overview (Required)
- Please delete LocaleMessage and use LocaledString

### PR DESCRIPTION
**Pull request by netcafeohashi**
## Issue
- close #290

## Overview (Required)
- Delete File LocaleMessage.kt 25183e9 

There may not be a place to replace LocaledString. 🤔

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry you can delete LocaleMessage 🙇 
But I want to delete SessionMessage 🙇

**Comment by netcafeohashi** [comment]
@takahirom 
I want to Revert to 25183e9 and delete SessionMessage?

**Comment by takahirom** [comment]
I don't want to revert it.
I don't know why LocaleMessage is exists 😭

**Comment by netcafeohashi** [comment]
@takahirom 
LocaleMessage と SessionMessage を削除して LocaledStringに置き換えます。

**Comment by takahirom** [comment]
Sorry 🙇 Thank you for contributing 👍

**Pull request merged**
