### PR TITLE
Add license feature

### LINKED ISSUE #146: Add license feature
## Overview (Required)
- You can use https://developers.google.com/android/guides/opensource
image

### PR DESCRIPTION
**Pull request by NUmeroAndDev**
## Issue
- close #146

## Overview (Required)
- Implements license screen.

## Links
- https://developers.google.com/android/guides/opensource

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by NUmeroAndDev** [comment]
Was a Toolbar necessary?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you for tackling this issue 🥇  
How about using DI for activity like this 👀 
https://github.com/DroidKaigi/conference-app-2019/commit/7d012d03829ce330a13022048a29f3206969b654

**Comment by NUmeroAndDev** [comment]
@takahirom 
Thank you for the advice.
I could not think of using DI.

Please check 🙇

**Comment by takahirom** [comment]
Thank you for tackling this issue 🥇

**Pull request merged**
