### PR TITLE
Support Deep Link

### LINKED ISSUE #67: Add deeplink support
## Overview (Required)
- We can use navigation architecture component support

### PR DESCRIPTION
**Pull request by yt-tkhs**
## Issue
- close #67

## Overview (Required)
- Implement deep link support.
- There are 2 types of behaviors.
    - Intent with `FLAG_ACTIVITY_NEW_TASK` (e.g. Twitter) : The app is launched as new task. we can go back to SessionPagesFragment. 
    - Intent without `FLAG_ACTIVITY_NEW_TASK` (e.g. Slack): The app is launched as a part of other app's task. we cannot go back to SessionPagesFragment and back and up will finish the app.

## Links
- The behavior is described in: https://issuetracker.google.com/issues/112452066 (comment no.3)

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by satsukies** [comment]
:eyes:

**Comment by satsukies** [comment]
@yt-tkhs 
Thank you for your contribution!
it does not work deeplink on my phone 😢 
Could you please check your codes?

I'm recommend to use App Links Assistant on Android Studio when you check deeplink implementation.

**Comment by yt-tkhs** [comment]
Hmm it's strange... it worked for me 😇
However, when I use App Links Assistant as your recommend, the notation of intent-filter has been changed automatically. So I followed it.
could you please check it again 🙇 

Btw Navigation Component has the feature that generating `<intent-filter>` by defining`<nav-graph>`, but it's not worked by the error below 😢:
```
Merging Errors: Error: Referenced navigation file with navigationXmlId = navigation not found android debug manifest, line 27 
```

**Comment by satsukies** [comment]
Thank you for checking!
I'll check later ASAP!

Ummm, I guess my environment not good, so I'll check it the same time.

**Comment by satsukies** [comment]
@yt-tkhs 
Deep Link worked!

But this branch has conflicting, could you please resolve conflict?:bow:

**Comment by yt-tkhs** [comment]
The conflict has been resolved 🙏

**Comment by satsukies** [comment]
@yt-tkhs 
Thanks a lot!

But, it looks like build failed 😢 
My guess is caused by bump up navigation version 👀 
According to the release notes, 1.0.0-alpha09 has breaking change about `fromBundle()`.
It seems that `SessionSurveyFragment.kt` has error by that changes.
Could you please check it? 🙇

**Comment by yt-tkhs** [comment]
I fixed the builder error so could you please re-review 🙇

**Comment by satsukies** [comment]
:eyes:

**Pull request merged**
