### PR TITLE
Enable org.gradle.parallel for faster build

### PR DESCRIPTION
**Pull request by miga9**
## Issue
There's no issues filed for this.

## Overview (Required)
I enabled `org.gradle.parallel` to take advantage of the multi-module setup. The build will run tasks in parallel where possible.

The amount of improved build time depends on the spec of your machine, but it should be faster in general.

Gradle scan reports
Enabled: https://scans.gradle.com/s/y5azqvabdv5yq
Disabled: https://scans.gradle.com/s/rz3r5yqbwt7ji

### CODE REVIEW

**Comment by miga9** [comment]
I think there must be something flaky on this test that failed above. 
`io.github.droidkaigi.confsched2019.announcement.ui.store.AnnouncementStoreTest.loadingState`

I just force-pushed to trigger another check. (curious to know whether there is a re-test/re-run command that is set up in this project's CircleCi integration.)

**Comment by takahirom** [comment]
I don't know that! Thanks 👍 

> take advantage of the multi-module setup. The build will run tasks in parallel where possible.

**Comment by takahirom** [comment]
Gradle scan reports are very cool 🆒

**Comment by miga9** [comment]
@takahirom Thanks for looking at it so fast :)
I updated the Overview to include the steps I took for the benchmark.

**Pull request merged**
